# Final Raw Data Frame

In [1]:
import pandas as pd

In [6]:
df_1 = pd.read_csv("../raw_data/Raw_data_new_version_part_one_Garrit.csv")

In [14]:
df_1

,Ticker,2023 Ordinary Shares Number,2023 Share Issued,2023 Net Debt,2023 Total Debt,2023 Tangible Book Value,2023 Invested Capital,2023 Working Capital,2023 Net Tangible Assets,2023 Common Stock Equity,...,2024 Other Investments,2024 Investment Properties,2024 Current Notes Payable,2024 Provision For Doubtful Accounts,2024 Minimum Pension Liabilities,2023 Depletion Income Statement,2022 Depletion Income Statement,2021 Depletion Income Statement,2020 Depletion Income Statement,2019 Depletion Income Statement
0,A,292123241.0,292123241.0,1.145000e+09,2.735000e+09,1.410000e+09,8.580000e+09,2.583000e+09,1.410000e+09,5.845000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AA,178472464.0,178472464.0,8.670000e+08,1.915000e+09,4.068000e+09,6.062000e+09,1.375000e+09,4.068000e+09,4.251000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AACG,64000260.0,64585618.0,NaN,2.260687e+07,-1.421377e+08,1.130379e+08,-2.439576e+08,-1.421377e+08,1.130379e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AACI,8072849.0,8072849.0,2.504155e+06,2.564439e+06,1.683079e+07,1.939523e+07,-8.493234e+06,1.683079e+07,1.683079e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AACIW,8072849.0,8072849.0,2.504155e+06,2.564439e+06,1.683079e+07,1.939523e+07,-8.493234e+06,1.683079e+07,1.683079e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1514,CULP,12327414.0,12327414.0,NaN,6.252000e+06,8.682800e+07,8.908000e+07,5.149600e+07,8.682800e+07,8.908000e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1515,CURI,53286000.0,53286000.0,NaN,4.283000e+06,2.770300e+07,7.264600e+07,2.189200e+07,2.770300e+07,7.264600e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1516,CURIW,53286000.0,53286000.0,NaN,4.283000e+06,2.770300e+07,7.264600e+07,2.189200e+07,2.770300e+07,7.264600e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1517,CURV,103774813.0,103774813.0,3.156520e+08,5.474290e+08,-2.386240e+08,9.899700e+07,-5.120600e+07,-2.386240e+08,-2.302240e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1518,CUTR,19948803.0,19948803.0,2.750830e+08,4.300230e+08,-1.731690e+08,2.468650e+08,1.814380e+08,-1.731690e+08,-1.718300e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df_2 = pd.read_csv("../raw_data/Raw_data_new_version_part_two_Guillaume.csv")

In [13]:
df_2

,Ticker,2023 Treasury Shares Number,2023 Ordinary Shares Number,2023 Share Issued,2023 Net Debt,2023 Total Debt,2023 Tangible Book Value,2023 Invested Capital,2023 Working Capital,2023 Net Tangible Assets,...,2023 Receiptsfrom Government Grants,2022 Interest Received Direct,2022 Receiptsfrom Government Grants,2021 Interest Received Direct,2021 Receiptsfrom Government Grants,2020 Interest Received Direct,2020 Receiptsfrom Government Grants,2019 Interest Received Direct,2019 Receiptsfrom Government Grants,2024 Interest Received Cfi
0,CUZ,2536583.0,1.517992e+08,1.543358e+08,2.451580e+09,2.510975e+09,4.413484e+09,6.981778e+09,-2.898570e+08,4.413484e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CVAC,NaN,2.239887e+08,2.239887e+08,NaN,4.182400e+07,4.885960e+08,5.169410e+08,2.919920e+08,4.885960e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CVBF,0.0,1.393450e+08,1.393450e+08,1.780499e+09,2.070000e+09,1.296860e+09,4.147972e+09,NaN,1.296860e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CVCO,671801.0,8.665324e+06,9.337125e+06,NaN,2.167800e+07,8.319490e+08,9.762860e+08,5.111880e+08,8.319490e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CVE,0.0,1.871869e+09,1.871869e+09,5.060000e+09,9.945000e+09,2.525600e+10,3.546600e+10,3.498000e+09,2.577500e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1620,KAVL,0.0,2.793385e+06,2.793385e+06,2.658120e+05,1.850246e+06,2.087802e+06,1.435558e+07,1.943639e+06,2.088702e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1621,KB,24847247.0,3.786638e+08,4.035111e+08,9.001275e+13,1.213890e+14,5.497895e+13,1.777300e+14,NaN,5.497895e+13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1622,KBDC,NaN,6.502164e+07,6.502164e+07,6.552500e+08,6.893190e+08,6.830560e+08,1.372375e+09,NaN,6.830560e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1623,KBH,25408951.0,7.586703e+07,1.012760e+08,9.625560e+08,1.716429e+09,3.810140e+09,5.500038e+09,5.435652e+09,3.810140e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1624,KBR,46646024.0,1.350676e+08,1.817136e+08,1.528000e+09,2.056000e+09,-1.344000e+09,3.215000e+09,7.900000e+07,-1.344000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df_3 = pd.read_csv("../raw_data/Raw_data_new_version_part_three_Jorge.csv")

In [12]:
df_3

,Ticker,2023 Treasury Shares Number,2023 Ordinary Shares Number,2023 Share Issued,2023 Total Debt,2023 Tangible Book Value,2023 Invested Capital,2023 Working Capital,2023 Net Tangible Assets,2023 Capital Lease Obligations,...,2019 Taxes Refund Paid Direct,2024 Loans Receivable,2024 Current Deferred Taxes Liabilities,2024 Purchase Of Investment Properties,2023 Change In Dividend Payable,2022 Change In Dividend Payable,2021 Change In Dividend Payable,2020 Change In Dividend Payable,2019 Change In Dividend Payable,2024 Cash From Discontinued Operating Activities
0,KC,243187335.0,3.562097e+09,3.805285e+09,1.722470e+09,1.449950e+09,8.101048e+09,-7.304660e+08,1.449950e+09,5.115740e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,KCGI,0.0,1.144273e+07,1.144273e+07,1.100250e+06,3.359112e+07,3.469137e+07,-2.023602e+06,3.359112e+07,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,KD,1900000.0,2.277000e+08,2.296000e+08,4.244000e+09,3.820000e+08,4.586000e+09,9.500000e+07,3.820000e+08,1.023000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,KDP,NaN,1.390446e+09,1.390446e+09,1.482400e+10,-1.781300e+10,3.886700e+10,-5.541000e+09,-1.781300e+10,1.633000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,KE,4706000.0,2.472400e+07,2.943000e+07,2.814540e+08,4.996480e+08,8.054480e+08,4.542790e+08,4.996480e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1592,RAIL,NaN,1.790344e+07,1.790344e+07,7.385200e+07,-4.620600e+07,-1.679100e+07,4.306000e+07,-4.620600e+07,4.443700e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1593,RAMP,87400000.0,6.660000e+07,1.540000e+08,4.717200e+07,5.530920e+08,9.260760e+08,5.397300e+08,5.530920e+08,4.717200e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1790000.0
1594,RAND,67895.0,2.581021e+06,2.648916e+06,1.625000e+07,6.081521e+07,7.706521e+07,NaN,6.081521e+07,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1595,RANI,NaN,2.603600e+07,2.603600e+07,3.009900e+07,1.286600e+07,4.224700e+07,4.285800e+07,1.286600e+07,7.180000e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1596,RAPT,NaN,3.439831e+07,3.439831e+07,6.906000e+06,1.470350e+08,1.470350e+08,1.399460e+08,1.470350e+08,6.906000e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_4 = pd.read_csv("../raw_data/Raw_data_new_version_part_four_Manon.csv")

In [11]:
df_4

,Ticker,2023 Treasury Shares Number,2023 Ordinary Shares Number,2023 Share Issued,2023 Total Debt,2023 Tangible Book Value,2023 Invested Capital,2023 Working Capital,2023 Net Tangible Assets,2023 Capital Lease Obligations,...,2024 Receivables Adjustments Allowances,2024 Securities Amortization,2024 Liabilities Heldfor Sale Non Current,2024 Non Current Accounts Receivable,2024 Sale Of Intangibles,2024 Investmentsin Joint Venturesat Cost,2024 Purchase Of Investment Properties,2024 Duefrom Related Parties Non Current,2024 Unrealized Gain Loss,2024 Excess Tax Benefit From Stock Based Compensation
0,RARE,9559.0,82315590.0,82325149.0,4.316900e+07,6.473700e+07,2.754140e+08,451747000.0,6.473700e+07,4.316900e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RAVE,10935605.0,14154453.0,25090058.0,1.421000e+06,1.006300e+07,1.039100e+07,4636000.0,1.006300e+07,1.421000e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,RAY,NaN,17500000.0,17500000.0,8.797200e+04,2.113851e+07,2.113851e+07,17837091.0,2.113851e+07,8.797200e+04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,RAYA,NaN,12450000.0,12450000.0,2.167398e+06,2.017024e+07,2.236949e+07,8886603.0,2.017024e+07,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,RBA,0.0,182843942.0,182843942.0,4.602600e+09,-2.434400e+09,8.106200e+09,471300000.0,-2.434400e+09,1.513100e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1588,ZVIA,0.0,54220017.0,54220017.0,1.948000e+06,8.635500e+07,8.987800e+07,54970000.0,8.635500e+07,1.948000e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1589,ZVRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1590,ZVSA,6.0,405205.0,405211.0,8.656000e+03,-7.573306e+06,1.107460e+07,-6841639.0,-7.573305e+06,8.656000e+03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1591,ZYME,NaN,70115997.0,70115997.0,2.672200e+07,4.275060e+08,4.648060e+08,357163000.0,4.275060e+08,2.672200e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1592,ZYXI,8545044.0,32933776.0,41478820.0,7.616800e+07,1.757000e+07,1.037340e+08,69323000.0,1.757000e+07,1.856300e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#concat_df= pd.concat([a_df, b_df], axis="index", sort=False)`
#add parameter `ignore_index=True` so they are stacked

In [17]:
raw_df = pd.concat([df_1, df_2, df_3, df_4], axis="index", sort=False, ignore_index=True)
raw_df

,Ticker,2023 Ordinary Shares Number,2023 Share Issued,2023 Net Debt,2023 Total Debt,2023 Tangible Book Value,2023 Invested Capital,2023 Working Capital,2023 Net Tangible Assets,2023 Common Stock Equity,...,2024 Interest Received Cfo,2023 Dividends Paid Direct,2022 Dividends Paid Direct,2021 Dividends Paid Direct,2020 Dividends Paid Direct,2019 Dividends Paid Direct,2024 Net Income From Tax Loss Carryforward,2024 Current Deferred Taxes Liabilities,2024 Change In Interest Payable,2024 Excise Taxes
0,A,292123241.0,292123241.0,1.145000e+09,2.735000e+09,1.410000e+09,8.580000e+09,2.583000e+09,1.410000e+09,5.845000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AA,178472464.0,178472464.0,8.670000e+08,1.915000e+09,4.068000e+09,6.062000e+09,1.375000e+09,4.068000e+09,4.251000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AACG,64000260.0,64585618.0,NaN,2.260687e+07,-1.421377e+08,1.130379e+08,-2.439576e+08,-1.421377e+08,1.130379e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AACI,8072849.0,8072849.0,2.504155e+06,2.564439e+06,1.683079e+07,1.939523e+07,-8.493234e+06,1.683079e+07,1.683079e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AACIW,8072849.0,8072849.0,2.504155e+06,2.564439e+06,1.683079e+07,1.939523e+07,-8.493234e+06,1.683079e+07,1.683079e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6329,ZVIA,54220017.0,54220017.0,NaN,1.948000e+06,8.635500e+07,8.987800e+07,5.497000e+07,8.635500e+07,8.987800e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6330,ZVRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6331,ZVSA,405205.0,405211.0,NaN,8.656000e+03,-7.573306e+06,1.107460e+07,-6.841639e+06,-7.573305e+06,1.107460e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6332,ZYME,70115997.0,70115997.0,NaN,2.672200e+07,4.275060e+08,4.648060e+08,3.571630e+08,4.275060e+08,4.648060e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6333,ZYXI,32933776.0,41478820.0,1.302600e+07,7.616800e+07,1.757000e+07,1.037340e+08,6.932300e+07,1.757000e+07,4.612900e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
raw_df.to_csv("../raw_data/raw_data_FINAL_ALL.csv", index=False)

In [22]:
pd.read_csv("../raw_data/raw_data_FINAL_ALL.csv")

,Ticker,2023 Ordinary Shares Number,2023 Share Issued,2023 Net Debt,2023 Total Debt,2023 Tangible Book Value,2023 Invested Capital,2023 Working Capital,2023 Net Tangible Assets,2023 Common Stock Equity,...,2024 Interest Received Cfo,2023 Dividends Paid Direct,2022 Dividends Paid Direct,2021 Dividends Paid Direct,2020 Dividends Paid Direct,2019 Dividends Paid Direct,2024 Net Income From Tax Loss Carryforward,2024 Current Deferred Taxes Liabilities,2024 Change In Interest Payable,2024 Excise Taxes
0,A,292123241.0,292123241.0,1.145000e+09,2.735000e+09,1.410000e+09,8.580000e+09,2.583000e+09,1.410000e+09,5.845000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AA,178472464.0,178472464.0,8.670000e+08,1.915000e+09,4.068000e+09,6.062000e+09,1.375000e+09,4.068000e+09,4.251000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AACG,64000260.0,64585618.0,NaN,2.260687e+07,-1.421377e+08,1.130379e+08,-2.439576e+08,-1.421377e+08,1.130379e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AACI,8072849.0,8072849.0,2.504155e+06,2.564439e+06,1.683079e+07,1.939523e+07,-8.493234e+06,1.683079e+07,1.683079e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AACIW,8072849.0,8072849.0,2.504155e+06,2.564439e+06,1.683079e+07,1.939523e+07,-8.493234e+06,1.683079e+07,1.683079e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6329,ZVIA,54220017.0,54220017.0,NaN,1.948000e+06,8.635500e+07,8.987800e+07,5.497000e+07,8.635500e+07,8.987800e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6330,ZVRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6331,ZVSA,405205.0,405211.0,NaN,8.656000e+03,-7.573306e+06,1.107460e+07,-6.841639e+06,-7.573305e+06,1.107460e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6332,ZYME,70115997.0,70115997.0,NaN,2.672200e+07,4.275060e+08,4.648060e+08,3.571630e+08,4.275060e+08,4.648060e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6333,ZYXI,32933776.0,41478820.0,1.302600e+07,7.616800e+07,1.757000e+07,1.037340e+08,6.932300e+07,1.757000e+07,4.612900e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN